// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Data.Models.Mp3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mp3Type")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Mp3s");
                });

            modelBuilder.Entity("Data.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Data.Models.PlaylistMp3", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("Mp3Id")
                        .HasColumnType("int");

                    b.HasKey("PlaylistId", "Mp3Id");

                    b.HasIndex("Mp3Id");

                    b.ToTable("PlaylistMp3s");
                });

            modelBuilder.Entity("Data.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Data.Models.ShoppingCartMp3", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.Property<int>("Mp3Id")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId", "Mp3Id");

                    b.HasIndex("Mp3Id");

                    b.ToTable("ShoppingCartMp3s");
                });

            modelBuilder.Entity("Data.Models.Mp3", b =>
                {
                    b.HasOne("Data.Models.Account", "Account")
                        .WithMany("Mp3s")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data.Models.Playlist", b =>
                {
                    b.HasOne("Data.Models.Account", "Account")
                        .WithMany("Playlists")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data.Models.PlaylistMp3", b =>
                {
                    b.HasOne("Data.Models.Mp3", "Mp3")
                        .WithMany("PlaylistMp3s")
                        .HasForeignKey("Mp3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.Playlist", "Playlist")
                        .WithMany("PlaylistMp3s")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mp3");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Data.Models.ShoppingCart", b =>
                {
                    b.HasOne("Data.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data.Models.ShoppingCartMp3", b =>
                {
                    b.HasOne("Data.Models.Mp3", "Mp3")
                        .WithMany("ShoppingCartMp3s")
                        .HasForeignKey("Mp3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("ShoppingCartMp3s")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mp3");

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("Data.Models.Account", b =>
                {
                    b.Navigation("Mp3s");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Data.Models.Mp3", b =>
                {
                    b.Navigation("PlaylistMp3s");

                    b.Navigation("ShoppingCartMp3s");
                });

            modelBuilder.Entity("Data.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistMp3s");
                });

            modelBuilder.Entity("Data.Models.ShoppingCart", b =>
                {
                    b.Navigation("ShoppingCartMp3s");
                });
#pragma warning restore 612, 618
        }
    }
}
